name: .NET CI

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x' # Specify the .NET version you are using

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Test
        run: dotnet test --no-build --verbosity normal
